name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.3
